# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3612e6801dcf123e12a38a66cfff86717dd0915d8e1fa19f7868f4f2985958f14309f4dee223317770d6b3b74dfab655bcbd2a2319306a5bbee967735e88256f

test:
  secret_key_base: 1e92cfd2efdf8ce79fc446637284e6a98f9211b711ac617d6efc850e382a27bfb9c0f309fb23c1dfb8b7db370ad46c68e82c909947b41a54fbe43cdf97e1a636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
